#!/usr/bin/env bash

# SPDX-FileCopyrightText: © The Clara Framework Authors
#
# SPDX-License-Identifier: Apache-2.0

BASEDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)

if [ -z "${CLARA_HOME}" ]; then
    CLARA_HOME=${BASEDIR}
    export CLARA_HOME
fi

# find plugins directory
if [ -n "${CLARA_PLUGINS}" ]; then
    if [ ! -d "${CLARA_PLUGINS}" ]; then
        echo "Error: \$CLARA_PLUGINS is not a directory."
        exit 1
    fi
    plugins_dir="${CLARA_PLUGINS}"
else
    plugins_dir="${CLARA_HOME}/plugins"
fi

# set default classpath
if [ -z "${CLASSPATH}" ]; then
    CLASSPATH="${CLARA_HOME}/lib/*"

    # Add every plugin
    for plugin in "${plugins_dir}"/*/; do
        plugin=${plugin%*/}
        CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
    done

    CLASSPATH+=":${CLARA_HOME}/services/*"
    export CLASSPATH
fi

# set java.library.path
java_lib_path=
for plugin in "${plugins_dir}"/*/; do
    plugin=${plugin%*/}
    java_lib_path+=":${plugin}/lib"
done
if [ -n "${java_lib_path}" ]; then
    java_lib_path=${java_lib_path#:}
    case "$(uname)" in
        "Linux")
            export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${java_lib_path}
            ;;
        "Darwin")
            export DYLD_LIBRARY_PATH=${DYLD_LIBRARY_PATH:+$DYLD_LIBRARY_PATH:}${java_lib_path}
            ;;
        "*")
            ;;
    esac
fi

if [ -n "${JAVA_OPTS}" ]; then
    jvm_options=(${JAVA_OPTS})
else
    jvm_options=(-Xms1024m -XX:+UseNUMA)
fi

java_wrapper=${CLARA_HOME}/lib/clara/run-java

exec "${java_wrapper}" "${jvm_options[@]}" org.jlab.clara.sys.Dpe "$@"
