#!/usr/bin/env bash

# SPDX-FileCopyrightText: © The Clara Framework Authors
#
# SPDX-License-Identifier: Apache-2.0

BASEDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)

if [ -z "${CLARA_HOME}" ]; then
    CLARA_HOME=${BASEDIR}
    export CLARA_HOME
fi

# set default classpath
if [ -z "${CLASSPATH}" ]; then
    CLASSPATH="${CLARA_HOME}/lib/*"
    export CLASSPATH
fi

java_wrapper=${CLARA_HOME}/lib/clara/run-java

exec "${java_wrapper}" org.jlab.clara.msg.sys.Proxy "$@"
