#!/bin/bash

# SPDX-FileCopyrightText: © The Clara Framework Authors
#
# SPDX-License-Identifier: MIT-0

set -e

DEV_TAG=claradk-$CACHE_TAG
DEV_TAG=${DEV_TAG%-latest}

docker build --target build --tag $DOCKER_REPO:$DEV_TAG -f Dockerfile ..
docker build --tag $IMAGE_NAME -f Dockerfile ..
