#!/bin/sh

# SPDX-FileCopyrightText: © The Clara Framework Authors
#
# SPDX-License-Identifier: Apache-2.0

# Gradle task `cacheClasspath` creates the classpath file
# for each subproject at every build

if [ -n "${JAVA_HOME}" ]; then
    java_bin="${JAVA_HOME}/bin/java"
else
    java_bin=java
fi

if [ "$1" = "-t" ]; then
    shift
    cache_file=test_classpath
else
    cache_file=classpath
fi

subproject=$1
cache_file=${subproject}/build/tmp/${cache_file}
shift

class_path=$(cat "${cache_file}")


exec "${java_bin}" -cp "${class_path}" "$@"
