#!/bin/sh

# SPDX-FileCopyrightText: © The Clara Framework Authors
#
# SPDX-License-Identifier: Apache-2.0

if [ -n "$JAVA_HOME" ]; then
    java_bin="$JAVA_HOME/bin/java"
else
    java_bin=java
fi

exec "$java_bin" "$@"
