#!/bin/sh

# SPDX-FileCopyrightText: © The Clara Framework Authors
#
# SPDX-License-Identifier: Apache-2.0

resources_dir=./clara-shell/src/main/resources

export CLARA_COMMAND_WRAPPER=${resources_dir}/lib/cmd-wrapper
export CLARA_COMMAND_LOGGER=${resources_dir}/lib/cmd-logger
export CLARA_TEMPLATES_DIR=${resources_dir}/lib/templates

exec ./scripts/exec-class \
    clara-shell \
    org.jlab.clara.std.cli.ClaraShell "$@"
