# SPDX-FileCopyrightText: © The Clara Framework Authors
#
# SPDX-License-Identifier: MIT-0

name: Clara CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Cache Gradle wrapper and dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper/dists
        key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle', 'gradle/**') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Prepare environment
      run: |
        echo "CLARA_HOME=$HOME/clara-java" >> $GITHUB_ENV
        echo "CLARA_USER_DATA=$HOME/clara-java" >> $GITHUB_ENV
        echo "CLARA_CONNECTION_TIMEOUT=5000" >> $GITHUB_ENV
        echo "CLARA_SUBSCRIPTION_TIMEOUT=5000" >> $GITHUB_ENV
        echo "CLARA_POST_CONNECTION_SLEEP=250" >> $GITHUB_ENV
        echo "CLARA_POST_SUBSCRIPTION_SLEEP=250" >> $GITHUB_ENV

    - name: Build with Gradle
      run: |
        ./gradlew -PciMode=true build codenarc spotbugs
        ./gradlew integration
